-- MySQL Script generated by MySQL Workbench
-- 06/03/15 22:45:20
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gamcultt
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gamcultt` ;
CREATE SCHEMA IF NOT EXISTS `gamcultt` DEFAULT CHARACTER SET utf8 ;
USE `gamcultt` ;

-- -----------------------------------------------------
-- Table `gamcultt`.`alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamcultt`.`alumno` ;

CREATE TABLE IF NOT EXISTS `gamcultt`.`alumno` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `paterno` VARCHAR(45) NOT NULL,
  `materno` VARCHAR(45) NOT NULL,
  `edad` INT(2) NOT NULL,
  `nombre_tutor` VARCHAR(100) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(20) NOT NULL,
  `Celular` VARCHAR(20          ) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamcultt`.`profesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamcultt`.`profesor` ;

CREATE TABLE IF NOT EXISTS `gamcultt`.`profesor` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `paterno` VARCHAR(45) NOT NULL,
  `materno` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `celular` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamcultt`.`casa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamcultt`.`casa` ;

CREATE TABLE IF NOT EXISTS `gamcultt`.`casa` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(85) NOT NULL,
  `direccion` VARCHAR(105) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `horario` VARCHAR(45) NOT NULL,
  `informacion` TEXT NOT NULL,
  `likn_maps` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamcultt`.`sala`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamcultt`.`sala` ;

CREATE TABLE IF NOT EXISTS `gamcultt`.`sala` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `casa` INT(11) NOT NULL,
  `nombre` VARCHAR(95) NOT NULL,
  `capacidad` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sala_casa1_idx` (`casa` ASC),
  CONSTRAINT `fk_sala_casa1`
    FOREIGN KEY (`casa`)
    REFERENCES `gamcultt`.`casa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamcultt`.`categoria_taller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamcultt`.`categoria_taller` ;

CREATE TABLE IF NOT EXISTS `gamcultt`.`categoria_taller` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamcultt`.`taller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamcultt`.`taller` ;

CREATE TABLE IF NOT EXISTS `gamcultt`.`taller` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `categoriaTaller` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_taller_CATEGORIA_TALLER1_idx` (`categoriaTaller` ASC),
  CONSTRAINT `fk_taller_CATEGORIA_TALLER1`
    FOREIGN KEY (`categoriaTaller`)
    REFERENCES `gamcultt`.`categoria_taller` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamcultt`.`clase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamcultt`.`clase` ;

CREATE TABLE IF NOT EXISTS `gamcultt`.`clase` (
  `profesor` INT(11) NOT NULL,
  `taller` INT(11) NOT NULL,
  `sala` INT(11) NOT NULL,
  `costo` DECIMAL(6,2) NOT NULL,
  `horario` VARCHAR(45) NOT NULL,
  `status` TINYINT(1) NOT NULL,
  PRIMARY KEY (`profesor`, `taller`),
  INDEX `fk_alumno_has_profesor_profesor1_idx` (`profesor` ASC),
  INDEX `fk_alumno_has_profesor_taller1_idx` (`taller` ASC),
  INDEX `fk_alumno_has_profesor_sala1_idx` (`sala` ASC),
  CONSTRAINT `fk_alumno_has_profesor_profesor1`
    FOREIGN KEY (`profesor`)
    REFERENCES `gamcultt`.`profesor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumno_has_profesor_sala1`
    FOREIGN KEY (`sala`)
    REFERENCES `gamcultt`.`sala` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumno_has_profesor_taller1`
    FOREIGN KEY (`taller`)
    REFERENCES `gamcultt`.`taller` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamcultt`.`alumno_clase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamcultt`.`alumno_clase` ;

CREATE TABLE IF NOT EXISTS `gamcultt`.`alumno_clase` (
  `alumno` INT(11) NOT NULL,
  `profesor` INT(11) NOT NULL,
  `taller` INT(11) NOT NULL,
  `alumno_clasecol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`alumno`, `profesor`, `taller`),
  INDEX `fk_alumno_has_clase_clase2_idx` (`profesor` ASC, `taller` ASC),
  INDEX `fk_alumno_has_clase_alumno2_idx` (`alumno` ASC),
  CONSTRAINT `fk_alumno_has_clase_alumno2`
    FOREIGN KEY (`alumno`)
    REFERENCES `gamcultt`.`alumno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumno_has_clase_clase2`
    FOREIGN KEY (`profesor` , `taller`)
    REFERENCES `gamcultt`.`clase` (`profesor` , `taller`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamcultt`.`categoria_evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamcultt`.`categoria_evento` ;

CREATE TABLE IF NOT EXISTS `gamcultt`.`categoria_evento` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamcultt`.`evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamcultt`.`evento` ;

CREATE TABLE IF NOT EXISTS `gamcultt`.`evento` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `sala` INT(11) NOT NULL,
  `categoriaEvento` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `informacion` TEXT NOT NULL,
  `horario` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(105) NOT NULL,
  `asistencia_estimada` INT(11) NOT NULL,
  `link_maps` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_evento_sala1_idx` (`sala` ASC),
  INDEX `fk_evento_CATEGORIA_EVENTO1_idx` (`categoriaEvento` ASC),
  CONSTRAINT `fk_evento_CATEGORIA_EVENTO1`
    FOREIGN KEY (`categoriaEvento`)
    REFERENCES `gamcultt`.`categoria_evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_sala1`
    FOREIGN KEY (`sala`)
    REFERENCES `gamcultt`.`sala` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamcultt`.`galeria_casa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamcultt`.`galeria_casa` ;

CREATE TABLE IF NOT EXISTS `gamcultt`.`galeria_casa` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `casa` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `extencion` VARCHAR(5) NOT NULL,
  `ruta` VARCHAR(85) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_galeria_CASA1_idx` (`casa` ASC),
  CONSTRAINT `fk_galeria_CASA1`
    FOREIGN KEY (`casa`)
    REFERENCES `gamcultt`.`casa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamcultt`.`galeria_evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamcultt`.`galeria_evento` ;

CREATE TABLE IF NOT EXISTS `gamcultt`.`galeria_evento` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `evento` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `extencion` VARCHAR(5) NOT NULL,
  `ruta` VARCHAR(85) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_galeria_evento_evento1_idx` (`evento` ASC),
  CONSTRAINT `fk_galeria_evento_evento1`
    FOREIGN KEY (`evento`)
    REFERENCES `gamcultt`.`evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamcultt`.`galeria_taller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamcultt`.`galeria_taller` ;

CREATE TABLE IF NOT EXISTS `gamcultt`.`galeria_taller` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `taller` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `extencion` VARCHAR(5) NOT NULL,
  `ruta` VARCHAR(85) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_galeria_taller_taller1_idx` (`taller` ASC),
  CONSTRAINT `fk_galeria_taller_taller1`
    FOREIGN KEY (`taller`)
    REFERENCES `gamcultt`.`taller` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamcultt`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamcultt`.`usuario` ;

CREATE TABLE IF NOT EXISTS `gamcultt`.`usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `paterno` VARCHAR(45) NOT NULL,
  `materno` VARCHAR(45) NOT NULL,
  `password` VARCHAR(10) NULL DEFAULT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `casa` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_casa1_idx` (`casa` ASC),
  CONSTRAINT `fk_usuario_casa1`
    FOREIGN KEY (`casa`)
    REFERENCES `gamcultt`.`casa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamcultt`.`propuesta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamcultt`.`propuesta` ;

CREATE TABLE IF NOT EXISTS `gamcultt`.`propuesta` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `representante` VARCHAR(105) NOT NULL,
  `objetivo` TEXT NOT NULL,
  `personas` INT(11) NULL DEFAULT NULL,
  `descripcion` TEXT NOT NULL,
  `correo` VARCHAR(85) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `asistencia_estimada` INT(11) NOT NULL,
  `usuario` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_propuesta_usuario1_idx` (`usuario` ASC),
  CONSTRAINT `fk_propuesta_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `gamcultt`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamcultt`.`visitante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamcultt`.`visitante` ;

CREATE TABLE IF NOT EXISTS `gamcultt`.`visitante` (
  `id` INT(11) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `apellido_paterno` VARCHAR(45) NOT NULL,
  `apellido_materno` VARCHAR(45) NULL DEFAULT NULL,
  `Edad` INT(2) NOT NULL,
  `Sexo` VARCHAR(10) NOT NULL,
  `Telefono` VARCHAR(20) NULL DEFAULT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Informacion` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gamcultt`.`visitante_evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gamcultt`.`visitante_evento` ;

CREATE TABLE IF NOT EXISTS `gamcultt`.`visitante_evento` (
  `visitante` INT(11) NOT NULL,
  `evento` INT(11) NOT NULL,
  `visitante_eventocol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`visitante`, `evento`),
  INDEX `fk_Visitante_has_evento_evento1_idx` (`evento` ASC),
  INDEX `fk_Visitante_has_evento_Visitante1_idx` (`visitante` ASC),
  CONSTRAINT `fk_Visitante_has_evento_evento1`
    FOREIGN KEY (`evento`)
    REFERENCES `gamcultt`.`evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visitante_has_evento_Visitante1`
    FOREIGN KEY (`visitante`)
    REFERENCES `gamcultt`.`visitante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
