package mx.ipn.escom.entidades;
// Generated 29/05/2015 09:21:20 AM by Hibernate Tools 3.6.0

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;

/**
 * Alumno generated by hbm2java
 */
@Entity
@Table(name = "alumno", catalog = "gamcultt"
)
public class Alumno implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    @Getter @Setter private Integer id;

    @Column(name = "nombre", nullable = false, length = 45)
    @Getter @Setter private String nombre;

    @Column(name = "paterno", nullable = false, length = 45)
    @Getter @Setter private String paterno;

    @Column(name = "materno", nullable = false, length = 45)
    @Getter @Setter private String materno;

    @Column(name = "edad", nullable = false)
    @Getter @Setter private Integer edad;

    @Column(name = "nombre_tutor", nullable = false, length = 100)
    @Getter @Setter private String nombreTutor;

    @Column(name = "Correo", nullable = false, length = 45)
    @Getter @Setter private String correo;

    @Column(name = "Telefono", nullable = false, length = 20)
    @Getter @Setter private String telefono;

    @Column(name = "Celular", length = 20)
    @Getter @Setter private String celular;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "alumno")
    @Getter @Setter private List<AlumnoClase> alumnoClases;

    public Alumno() {
    }

    public Alumno(String nombre, String paterno, String materno, Integer edad, String nombreTutor, String correo, String telefono) {
        this.nombre = nombre;
        this.paterno = paterno;
        this.materno = materno;
        this.edad = edad;
        this.nombreTutor = nombreTutor;
        this.correo = correo;
        this.telefono = telefono;
    }

    public Alumno(String nombre, String paterno, String materno, Integer edad, String nombreTutor, String correo, String telefono, String celular, List<AlumnoClase> alumnoClases) {
        this.nombre = nombre;
        this.paterno = paterno;
        this.materno = materno;
        this.edad = edad;
        this.nombreTutor = nombreTutor;
        this.correo = correo;
        this.telefono = telefono;
        this.celular = celular;
        this.alumnoClases = alumnoClases;
    }

}
