package mx.ipn.escom.entidades;
// Generated 29/05/2015 09:21:20 AM by Hibernate Tools 3.6.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.validator.constraints.NotBlank;

/**
 * AlumnoClase generated by hbm2java
 */
@Entity
@Table(name = "alumno_clase", catalog = "gamcultt")
@AllArgsConstructor
@NoArgsConstructor
public @Data class AlumnoClase implements java.io.Serializable {

    @EmbeddedId
    @AttributeOverrides({
        @AttributeOverride(name = "alumno", column = @Column(name = "alumno", nullable = false)),
        @AttributeOverride(name = "profesor", column = @Column(name = "profesor", nullable = false)),
        @AttributeOverride(name = "taller", column = @Column(name = "taller", nullable = false))})
    private AlumnoClaseId id;
    
    @NotBlank (message = "Debes de Seleccionar una Clase")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({
        @JoinColumn(name = "profesor", referencedColumnName = "profesor", nullable = false, insertable = false, updatable = false),
        @JoinColumn(name = "taller", referencedColumnName = "taller", nullable = false, insertable = false, updatable = false)})
    private Clase clase;

    @NotBlank (message = "Debes de Seleccionar un Alumno")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "alumno", nullable = false, insertable = false, updatable = false)
    private Alumno alumno;

}
