package mx.ipn.escom.entidades;
// Generated 29/05/2015 09:21:20 AM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Embeddable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * AlumnoClaseId generated by hbm2java
 */
@Embeddable
@AllArgsConstructor
@NoArgsConstructor
public @Data class AlumnoClaseId implements java.io.Serializable {

    @Column(name = "alumno", nullable = false)
    private Integer alumno;

    @Column(name = "profesor", nullable = false)
    private Integer profesor;

    @Column(name = "taller", nullable = false)
    private Integer taller;

}
