package mx.ipn.escom.entidades;
// Generated 29/05/2015 09:21:20 AM by Hibernate Tools 3.6.0

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Alumno generated by hbm2java
 */


@Entity
@Table(name = "alumno", catalog = "gamcultt")
@AllArgsConstructor
@NoArgsConstructor
public @Data class Alumno implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    private Integer id;

    @Column(name = "nombre", nullable = false, length = 45)
    private String nombre;

    @Column(name = "paterno", nullable = false, length = 45)
    private String paterno;

    @Column(name = "materno", nullable = false, length = 45)
    private String materno;

    @Column(name = "edad", nullable = false)
    private Integer edad;

    @Column(name = "nombre_tutor", nullable = false, length = 100)
    private String nombreTutor;

    @Column(name = "Correo", nullable = false, length = 45)
    private String correo;

    @Column(name = "Telefono", nullable = false, length = 20)
    private String telefono;

    @Column(name = "Celular", length = 20)
    private String celular;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "alumno")
    private List<AlumnoClase> alumnoClases;

}
