package mx.ipn.escom.entidades;
// Generated 29/05/2015 09:21:20 AM by Hibernate Tools 3.6.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;

/**
 * AlumnoClase generated by hbm2java
 */
@Entity
@Table(name = "alumno_clase", catalog = "gamcultt"
)
public class AlumnoClase implements java.io.Serializable {

    @EmbeddedId
    @AttributeOverrides({
        @AttributeOverride(name = "alumno", column = @Column(name = "alumno", nullable = false)),
        @AttributeOverride(name = "profesor", column = @Column(name = "profesor", nullable = false)),
        @AttributeOverride(name = "taller", column = @Column(name = "taller", nullable = false))})
    @Getter @Setter private AlumnoClaseId id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({
        @JoinColumn(name = "profesor", referencedColumnName = "profesor", nullable = false, insertable = false, updatable = false),
        @JoinColumn(name = "taller", referencedColumnName = "taller", nullable = false, insertable = false, updatable = false)})
    @Getter @Setter private Clase clase;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "alumno", nullable = false, insertable = false, updatable = false)
    @Getter @Setter private Alumno alumno;

    public AlumnoClase() {
    }

    public AlumnoClase(AlumnoClaseId id, Clase clase, Alumno alumno) {
        this.id = id;
        this.clase = clase;
        this.alumno = alumno;
    }
}
