package mx.ipn.escom.entidades;
// Generated 29/05/2015 09:21:20 AM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Embeddable;
import lombok.Getter;
import lombok.Setter;

/**
 * AlumnoClaseId generated by hbm2java
 */
@Embeddable
public class AlumnoClaseId implements java.io.Serializable {

    @Column(name = "alumno", nullable = false)
    @Getter @Setter private Integer alumno;

    @Column(name = "profesor", nullable = false)
    @Getter @Setter private Integer profesor;

    @Column(name = "taller", nullable = false)
    @Getter @Setter private Integer taller;

    public AlumnoClaseId() {
    }

    public AlumnoClaseId(Integer alumno, Integer profesor, Integer taller) {
        this.alumno = alumno;
        this.profesor = profesor;
        this.taller = taller;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof AlumnoClaseId)) {
            return false;
        }
        AlumnoClaseId castOther = (AlumnoClaseId) other;

        return (this.getAlumno() == castOther.getAlumno())
                && (this.getProfesor() == castOther.getProfesor())
                && (this.getTaller() == castOther.getTaller());
    }

    public int hashCode() {
        Integer result = 17;

        result = 37 * result + this.getAlumno();
        result = 37 * result + this.getProfesor();
        result = 37 * result + this.getTaller();
        return result;
    }

}
