package mx.ipn.escom.entidades;
// Generated 29/05/2015 09:21:20 AM by Hibernate Tools 3.6.0

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Pattern;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * CategoriaEvento generated by hbm2java
 */
@Entity
@Table(name = "categoria_evento", catalog = "gamcultt")
@AllArgsConstructor
@NoArgsConstructor
public @Data class CategoriaEvento implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    private Integer id;

    @Pattern(regexp = "^[a-zA-Záéíóúñ]{2,}$", message="Verifique el nombre")
    @Column(name = "nombre", nullable = false, length = 45)
    private String nombre;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "categoriaEvento")
    private List<Evento> eventos;

    public CategoriaEvento(Integer id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }


}
