package mx.ipn.escom.entidades;
// Generated 29/05/2015 09:21:20 AM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;

/**
 * CategoriaEvento generated by hbm2java
 */
@Entity
@Table(name = "categoria_evento", catalog = "gamcultt"
)
public class CategoriaEvento implements java.io.Serializable {

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @Getter @Setter private Integer id;

    @Column(name = "nombre", nullable = false, length = 45)
    @Getter @Setter private String nombre;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "categoriaEvento")
    @Getter @Setter private List<Evento> eventos;

    public CategoriaEvento() {
    }

    public CategoriaEvento(Integer id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }

    public CategoriaEvento(Integer id, String nombre, List<Evento> eventos) {
        this.id = id;
        this.nombre = nombre;
        this.eventos = eventos;
    }

}
