package mx.ipn.escom.entidades;
// Generated 29/05/2015 09:21:20 AM by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import java.util.List;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Min;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.validator.constraints.NotBlank;

/**
 * Clase generated by hbm2java
 */
@Entity
@Table(name = "clase", catalog = "gamcultt")
@AllArgsConstructor
@NoArgsConstructor
public @Data class Clase implements java.io.Serializable {

    @EmbeddedId
    @AttributeOverrides({
        @AttributeOverride(name = "profesor", column = @Column(name = "profesor", nullable = false)),
        @AttributeOverride(name = "taller", column = @Column(name = "taller", nullable = false))})
    private ClaseId id;

    @NotBlank(message = "Seleccione un Profesor")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "profesor", nullable = false, insertable = false, updatable = false)
    private Profesor profesor;

    @NotBlank(message = "Seleccione una Sala")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sala", nullable = false)
    private Sala sala;

    @NotBlank(message = "Seleccione un Taller")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "taller", nullable = false, insertable = false, updatable = false)
    private Taller taller;


    @Column(name = "status", nullable = false)
    private boolean status;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "clase")
    private List<AlumnoClase> alumnoClases;

    public Clase(ClaseId id, Profesor profesor, Sala sala, Taller taller, boolean status) {
        this.id = id;
        this.profesor = profesor;
        this.sala = sala;
        this.taller = taller;        
        this.status = status;
    }

}
