package mx.ipn.escom.entidades;
// Generated 29/05/2015 09:21:20 AM by Hibernate Tools 3.6.0

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Encargado generated by hbm2java
 */
@Entity
@Table(name = "encargado", catalog = "gamcultt"
)
public class Encargado implements java.io.Serializable {

    @Id @GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "usuario"))
    @GeneratedValue(generator = "generator")
    @Column(name = "id", unique = true, nullable = false)
    @Getter @Setter private Integer id;

    @OneToOne(fetch = FetchType.LAZY)
    @PrimaryKeyJoinColumn
    @Getter @Setter private Usuario usuario;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "casa", nullable = false)
    @Getter @Setter private Casa casa;
    
    @Column(name = "nombre", nullable = false, length = 45)
    @Getter @Setter private String nombre;

    @Column(name = "paterno", nullable = false, length = 45)
    @Getter @Setter private String apellidoPaterno;

    @Column(name = "materno", nullable = false, length = 45)
    @Getter @Setter private String apellidoMaterno;

    @Column(name = "telefono", length = 45)
    @Getter @Setter private String telefono;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "encargado")
    @Getter @Setter private List<Propuesta> propuestas;

    public Encargado() {
    }

    public Encargado(Usuario usuario, Casa casa) {
        this.usuario = usuario;
        this.casa = casa;
    }

    public Encargado(Usuario usuario, Casa casa, String telefono, List<Propuesta> propuestas) {
        this.usuario = usuario;
        this.casa = casa;
        this.telefono = telefono;
        this.propuestas = propuestas;
    }

}
