package mx.ipn.escom.entidades;
// Generated 29/05/2015 09:21:20 AM by Hibernate Tools 3.6.0

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Profesor generated by hbm2java
 */
@Entity
@Table(name = "profesor", catalog = "gamcultt")
@AllArgsConstructor
@NoArgsConstructor
public @Data class Profesor implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    private Integer id;

    @Column(name = "nombre", nullable = false, length = 45)
    private String nombre;

    @Column(name = "paterno", nullable = false, length = 45)
    private String paterno;

    @Column(name = "materno", nullable = false, length = 45)
    private String materno;

    @Column(name = "correo", nullable = false, length = 45)
    private String correo;

    @Column(name = "telefono", length = 20)
    private String telefono;

    @Column(name = "celular", length = 20)
    private String celular;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "profesor")
    private List<Clase> clases;

    public Profesor(String nombre, String paterno, String materno, String correo) {
        this.nombre = nombre;
        this.paterno = paterno;
        this.materno = materno;
        this.correo = correo;
    }


}
