package mx.ipn.escom.entidades;
// Generated 29/05/2015 09:21:20 AM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


/**
 * Propuesta generated by hbm2java
 */
@Entity
@Table(name = "propuesta", catalog = "gamcultt")
@AllArgsConstructor
@NoArgsConstructor
public @Data class Propuesta implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    private Integer id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usuario", nullable = false)
    private Usuario usuario;

    @Column(name = "representante", nullable = false, length = 105)
    private String representante;

    @Column(name = "objetivo", nullable = false, length = 65535)
    private String objetivo;

    @Column(name = "personas")
    private Integer personas;

    @Column(name = "descripcion", nullable = false, length = 65535)
    private String descripcion;

    @Column(name = "correo", nullable = false, length = 85)
    private String correo;

    @Column(name = "telefono", length = 20)
    private String telefono;

    @Column(name = "asistencia_estimada", nullable = false)
    private Integer asistenciaEstimada;


    public Propuesta(Usuario usuario, String representante, String objetivo, String descripcion, String correo, Integer asistenciaEstimada) {
        this.usuario = usuario;
        this.representante = representante;
        this.objetivo = objetivo;
        this.descripcion = descripcion;
        this.correo = correo;
        this.asistenciaEstimada = asistenciaEstimada;
    }

}
