package mx.ipn.escom.entidades;
// Generated 29/05/2015 09:21:20 AM by Hibernate Tools 3.6.0

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Min;
import javax.validation.constraints.Pattern;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.validator.constraints.NotBlank;

/**
 * Sala generated by hbm2java
 */
@Entity
@Table(name = "sala", catalog = "gamcultt")
@AllArgsConstructor
@NoArgsConstructor
public @Data class Sala implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    private Integer id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "casa", nullable = false)
    private Casa casa;

    @Pattern(regexp = "^[a-zA-Záéíóúñ\\s]{2,}$", message="Verifique el nombre")
    @Column(name = "nombre", nullable = false, length = 95)
    private String nombre;

    @Min(value=10, message = "Verifique la Capacidad")
    @Column(name = "capacidad", nullable = false)
    private int capacidad;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "sala")
    private List<Clase> clases;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "sala")
    private List<Evento> eventos;

    public Sala(Casa casa, String nombre, int capacidad) {
        this.casa = casa;
        this.nombre = nombre;
        this.capacidad = capacidad;
    }

    public String getCasa(String nombre) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
