package mx.ipn.escom.entidades;
// Generated 29/05/2015 09:21:20 AM by Hibernate Tools 3.6.0

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Taller generated by hbm2java
 */
@Entity
@Table(name = "taller", catalog = "gamcultt")
@AllArgsConstructor
@NoArgsConstructor
public @Data class Taller implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    private Integer id;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "categoria_taller", nullable = false)
    private CategoriaTaller categoriaTaller;

    @Column(name = "nombre", nullable = false, length = 45)
    private String nombre;

    @Column(name = "descripcion", nullable = false, length = 65535)
    private String descripcion;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "taller")
    private List<GaleriaTaller> galeriaTallers;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "taller")
    private List<Clase> clases;

    public Taller(CategoriaTaller categoriaTaller, String nombre, String descripcion) {
        this.categoriaTaller = categoriaTaller;
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
}
