package mx.ipn.escom.entidades;
// Generated 29/05/2015 09:21:20 AM by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Min;
import javax.validation.constraints.Pattern;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.validator.constraints.NotBlank;

/**
 * Taller generated by hbm2java
 */
@Entity
@Table(name = "taller", catalog = "gamcultt")
@AllArgsConstructor
@NoArgsConstructor
public @Data class Taller implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    private Integer id;
    
    @NotBlank(message = "Seleccione una Categoría del Taller")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "categoriaTaller", nullable = false)
    private CategoriaTaller categoriaTaller;

    @Pattern(regexp = "^[a-zA-Záéíóúñ\\s]{2,}$", message="Verifique el nombre")
    @Column(name = "nombre", nullable = false, length = 45)
    private String nombre;

    @Pattern(regexp = "^[a-zA-Záéíóúñ0-9\\s]{2,}$", message="Verifique la Descripción")
    @Column(name = "descripcion", nullable = false, length = 65535)
    private String descripcion;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "taller")
    private List<GaleriaTaller> galeriaTallers;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "taller")
    private List<Clase> clases;
    
    @Min(value=1, message = "El costo es incorrecto")
    @Column(name = "costo", nullable = false, precision = 6)
    private BigDecimal costo;

    @Column(name = "horario", nullable = false, length = 45)
    private String horario;

    public Taller(CategoriaTaller categoriaTaller, String nombre, String descripcion, BigDecimal costo, String horario) {
        this.categoriaTaller = categoriaTaller;
        this.nombre = nombre;
        this.costo = costo;
        this.horario = horario;
        this.descripcion = descripcion;
    }
}
