package mx.ipn.escom.entidades;
// Generated 29/05/2015 09:21:20 AM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Encargado generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "gamcultt")
@AllArgsConstructor
@NoArgsConstructor
public @Data class Usuario implements java.io.Serializable {

    @Id 
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    private Integer id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "casa", nullable = false)
    private Casa casa;
    
    @Column(name = "nombre", nullable = false, length = 45)
    private String nombre;

    @Column(name = "paterno", nullable = false, length = 45)
    private String paterno;

    @Column(name = "materno", nullable = false, length = 45)
    private String materno;

    @Column(name = "telefono", length = 45)
    private String telefono;

    @Column(name = "correo", nullable = false, length = 45)
    private String correo;
    
    @Column(name = "password",  length = 10)
    private String password;

    @Column(name = "estado", nullable = false)
    private Boolean estado;


}
