package mx.ipn.escom.entidades;
// Generated 29/05/2015 09:21:20 AM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.Pattern;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotBlank;

/**
 * Encargado generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "gamcultt")
@AllArgsConstructor
@NoArgsConstructor
public @Data class Usuario implements java.io.Serializable {

    @Id 
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    private Integer id;

    @NotBlank(message = "Seleccione una Casa")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "casa", nullable = false)
    private Casa casa;
    
    @Pattern(regexp = "^[a-zA-Záéíóúñ\\s]{2,}$", message="Verifique el Nombre")
    @Column(name = "nombre", nullable = false, length = 45)
    private String nombre;

    @Pattern(regexp = "^[a-zA-Záéíóúñ]{2,}$", message="Verifique el Apellido Paterno")
    @Column(name = "paterno", nullable = false, length = 45)
    private String paterno;

    @Pattern(regexp = "^[a-zA-Záéíóúñ]{2,}$", message="Verifique el Apellido Materno")
    @Column(name = "materno", nullable = false, length = 45)
    private String materno;

    @Pattern(regexp = "^[1-9]{2}-[0-9]{2}-[0-9]{2}-[0-9]{2}$", message="Verifique el Teléfono")
    @Column(name = "telefono", length = 45)
    private String telefono;

    @Email(message = "Verfique el Correo")
    @Column(name = "correo", nullable = false, length = 45)
    private String correo;
    
    @Pattern(regexp = "^[a-zA-ZÁáÀàÉéÈèÍíÌìÓóÒòÚúÙùÑñüÜ0-9!@#\\$%\\^&\\*\\?_~\\/]{8,10}$", message="Verifique la Contraseña")
    @Column(name = "password",  length = 10)
    private String password;

    @Column(name = "estado", nullable = false)
    private Boolean estado;


}
