package mx.ipn.escom.entidades;
// Generated 29/05/2015 09:21:20 AM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "gamcultt"
)
public class Usuario implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    @Getter @Setter private Integer id;
    
    @Column(name = "correo", nullable = false, length = 45)
    @Getter @Setter private String correo;
    
    @Column(name = "password", nullable = false, length = 45)
    @Getter @Setter private String password;

    @Column(name = "tipo", nullable = false)
    @Getter @Setter private boolean tipo;

    @OneToOne(fetch = FetchType.LAZY, mappedBy = "usuario")
    @Getter @Setter private Encargado encargado;

    public Usuario() {}

    public Usuario(String nombre, String apellidoPaterno, String apellidoMaterno, String correo, boolean tipo) {
        this.correo = correo;
        this.tipo = tipo;
    }

    public Usuario(String nombre, String apellidoPaterno, String apellidoMaterno, String correo, boolean tipo, Encargado encargado) {
        this.correo = correo;
        this.tipo = tipo;
        this.encargado = encargado;
    }

}
