package mx.ipn.escom.entidades;
// Generated 29/05/2015 09:21:20 AM by Hibernate Tools 3.6.0

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Visitante generated by hbm2java
 */
@Entity
@Table(name = "visitante", catalog = "gamcultt")
@AllArgsConstructor
@NoArgsConstructor
public @Data class Visitante implements java.io.Serializable {

    @Id
    @Column(name = "id", unique = true, nullable = false)
    private Integer id;

    @Column(name = "Nombre", nullable = false, length = 45)
    private String nombre;

    @Column(name = "apellido_paterno", nullable = false, length = 45)
    private String apellidoPaterno;

    @Column(name = "apellido_materno", length = 45)
    private String apellidoMaterno;

    @Column(name = "Edad", nullable = false)
    private Integer edad;

    @Column(name = "Sexo", nullable = false, length = 10)
    private String sexo;

    @Column(name = "Telefono", length = 20)
    private String telefono;

    @Column(name = "Correo", nullable = false, length = 45)
    private String correo;

    @Column(name = "Informacion")
    private Boolean informacion;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "visitante")
    private List<VisitanteEvento> visitanteEventos;

    public Visitante(Integer id, String nombre, String apellidoPaterno, Integer edad, String sexo, String correo) {
        this.id = id;
        this.nombre = nombre;
        this.apellidoPaterno = apellidoPaterno;
        this.edad = edad;
        this.sexo = sexo;
        this.correo = correo;
    }

}
