package mx.ipn.escom.entidades;
// Generated 29/05/2015 09:21:20 AM by Hibernate Tools 3.6.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.validator.constraints.NotBlank;

/**
 * VisitanteEvento generated by hbm2java
 */
@Entity
@Table(name = "visitante_evento", catalog = "gamcultt")
@AllArgsConstructor
@NoArgsConstructor
public @Data class VisitanteEvento implements java.io.Serializable {

    @EmbeddedId
    @AttributeOverrides({
        @AttributeOverride(name = "visitante", column = @Column(name = "visitante", nullable = false)),
        @AttributeOverride(name = "evento", column = @Column(name = "evento", nullable = false))})
    private VisitanteEventoId id;

    @NotBlank(message = "Seleccione un Evento")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "evento", nullable = false, insertable = false, updatable = false)
    private Evento evento;

    @NotBlank(message = "Seleccione un Visitante")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "visitante", nullable = false, insertable = false, updatable = false)
    private Visitante visitante;


}
