package mx.ipn.escom.entidades;
// Generated 29/05/2015 09:21:20 AM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Embeddable;
import lombok.Getter;
import lombok.Setter;

/**
 * VisitanteEventoId generated by hbm2java
 */
@Embeddable
public class VisitanteEventoId implements java.io.Serializable {

    @Column(name = "visitante", nullable = false)
    @Getter @Setter private Integer visitante;

    @Column(name = "evento", nullable = false)
    @Getter @Setter private Integer evento;

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof VisitanteEventoId)) {
            return false;
        }
        VisitanteEventoId castOther = (VisitanteEventoId) other;

        return (this.getVisitante() == castOther.getVisitante())
                && (this.getEvento() == castOther.getEvento());
    }

    public int hashCode() {
        Integer result = 17;

        result = 37 * result + this.getVisitante();
        result = 37 * result + this.getEvento();
        return result;
    }

    public VisitanteEventoId() {
    }

    public VisitanteEventoId(Integer visitante, Integer evento) {
        this.visitante = visitante;
        this.evento = evento;
    }

}
