package mx.ipn.escom.entidades;
// Generated 29/05/2015 09:21:20 AM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;

/**
 * Visitante generated by hbm2java
 */
@Entity
@Table(name = "visitante", catalog = "gamcultt"
)
public class Visitante implements java.io.Serializable {

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @Getter @Setter private Integer id;

    @Column(name = "Nombre", nullable = false, length = 45)
    @Getter @Setter private String nombre;

    @Column(name = "apellido_paterno", nullable = false, length = 45)
    @Getter @Setter private String apellidoPaterno;

    @Column(name = "apellido_materno", length = 45)
    @Getter @Setter private String apellidoMaterno;

    @Column(name = "Edad", nullable = false)
    @Getter @Setter private Integer edad;

    @Column(name = "Sexo", nullable = false, length = 10)
    @Getter @Setter private String sexo;

    @Column(name = "Telefono", length = 20)
    @Getter @Setter private String telefono;

    @Column(name = "Correo", nullable = false, length = 45)
    @Getter @Setter private String correo;

    @Column(name = "Informacion")
    @Getter @Setter private Boolean informacion;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "visitante")
    @Getter @Setter private List<VisitanteEvento> visitanteEventos;

    public Visitante() {
    }

    public Visitante(Integer id, String nombre, String apellidoPaterno, Integer edad, String sexo, String correo) {
        this.id = id;
        this.nombre = nombre;
        this.apellidoPaterno = apellidoPaterno;
        this.edad = edad;
        this.sexo = sexo;
        this.correo = correo;
    }

    public Visitante(Integer id, String nombre, String apellidoPaterno, String apellidoMaterno, Integer edad, String sexo, String telefono, String correo, Boolean informacion, List<VisitanteEvento> visitanteEventos) {
        this.id = id;
        this.nombre = nombre;
        this.apellidoPaterno = apellidoPaterno;
        this.apellidoMaterno = apellidoMaterno;
        this.edad = edad;
        this.sexo = sexo;
        this.telefono = telefono;
        this.correo = correo;
        this.informacion = informacion;
        this.visitanteEventos = visitanteEventos;
    }

}
