package mx.ipn.escom.entidades;
// Generated 29/05/2015 09:21:20 AM by Hibernate Tools 3.6.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;

/**
 * VisitanteEvento generated by hbm2java
 */
@Entity
@Table(name = "visitante_evento", catalog = "gamcultt"
)
public class VisitanteEvento implements java.io.Serializable {

    @EmbeddedId
    @AttributeOverrides({
        @AttributeOverride(name = "visitante", column = @Column(name = "visitante", nullable = false)),
        @AttributeOverride(name = "evento", column = @Column(name = "evento", nullable = false))})
    @Getter @Setter private VisitanteEventoId id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "evento", nullable = false, insertable = false, updatable = false)
    @Getter @Setter private Evento evento;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "visitante", nullable = false, insertable = false, updatable = false)
    @Getter @Setter private Visitante visitante;

    @Column(name = "visitante_eventocol", length = 45)
    @Getter @Setter private String visitanteEventocol;

    public VisitanteEvento() {
    }

    public VisitanteEvento(VisitanteEventoId id, Evento evento, Visitante visitante) {
        this.id = id;
        this.evento = evento;
        this.visitante = visitante;
    }

    public VisitanteEvento(VisitanteEventoId id, Evento evento, Visitante visitante, String visitanteEventocol) {
        this.id = id;
        this.evento = evento;
        this.visitante = visitante;
        this.visitanteEventocol = visitanteEventocol;
    }

}
